### PR TITLE
BC: Mass sampling, IMF cor. factor, improved Ferrini IMF

### PR DESCRIPTION
**Pull request by becot85**
Hi Christian,

This contains the new parameters (init functions) that are needed for codes that are externally using OMEGA and SYGMA (e.g., three-zone code, Monte Carlo code, GAMMA).

I added the option to throw an incomplete IMF as an input. I added the IMF correction factor, which gives maximum flexibility to play with the yields (needed for the 3-zone code, and will be needed if I do the binary project with Chris).

I made an approximated Ferrini IMF that has an analytical solution for its integration.

Your SYGMA test suite worked.

### CODE REVIEW

**Comment by becot85** [comment]
Response to "How can we make sure the inexperienced user is not confusing this with the sn1a_table variable?"
Are you referring to the sn1a_table_in parameter? It might be confusing, but he/she can always look at the original sn1a_table parameter?

**Comment by chritter** [comment]
Yes, I also place my comments directly in the code which allows to see to what variable I refer to. I would suggest to mention in the variable description that this is a variable for a certain purpose.

**Comment by becot85** [comment]
But why sn1a_table_in is a problem, but not yield_table_in ?..

**Comment by chritter** [comment]
With comments such as  

> critter1 commented on chem_evol.py in 0b1737b an hour ago 

you can click on the commit number 0b1737b to browse the code and slide down to my comments. To your other question: I agree that the other *_in variables carry the same risk of confusion.

**Pull request closed without merging**
